### PR TITLE
Allow user to access fastboot instance in fastboot-testing.js config

### PR DESCRIPTION
**Pull request by haochuan**
Change for https://github.com/embermap/ember-cli-fastboot-testing/issues/159

### CODE REVIEW

**Comment by ryanto** [comment]
Thanks!

Don't worry about the 2.8 test failure, that's broken for master as well.

**Comment by ryanto** [comment]
I think a good test for this PR would be to modify the globals using the `setupFastboot` function. Then have a test that visits a route/template that renders the globals and make sure the modified global is present.

**Comment by haochuan** [comment]
sure thanks, I will update the PR with test

**Comment by haochuan** [comment]
@ryanto Added a test for using `setupFastboot` to modify `sandboxGlobals`. Please let me know if that looks good to you. Thanks!

**Pull request merged**
